<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Supplier;
use App\Models\Condominium;

class SupplierSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Buscar condomínios existentes
        $condominiums = Condominium::all();

        if ($condominiums->isEmpty()) {
            $this->command->info('Nenhum condomínio encontrado. Execute o CondominiumSeeder primeiro.');
            return;
        }

        $suppliers = [
            // Fornecimento de gás
            [
                'condominium_id' => $condominiums->first()->id,
                'company_name' => 'Gás Natural Express Ltda',
                'trade_name' => 'Gás Express',
                'cnpj' => '12.345.678/0001-90',
                'cpf' => null,
                'supplier_type' => 'company',
                'category' => 'gas_supply',
                'contact_name' => 'João Silva',
                'email' => 'contato@gasexpress.com',
                'phone' => '(11) 3456-7890',
                'mobile' => '(11) 99876-5432',
                'address' => 'Rua do Gás, 123',
                'number' => '123',
                'cep' => '01234-567',
                'city' => 'São Paulo',
                'state' => 'SP',
                'district' => 'Vila Industrial',
                'services_description' => 'Fornecimento de gás natural para condomínios residenciais.',
                'hourly_rate' => null,
                'monthly_rate' => 850.00,
                'contract_start' => '2024-01-01',
                'contract_end' => '2024-12-31',
                'status' => 'active',
                'evaluation' => 4.5,
                'notes' => 'Fornecedor confiável, sempre pontual.',
                'emergency_contact' => '(11) 99999-1111',
                'active' => true
            ],
            // Manutenção de portões
            [
                'condominium_id' => $condominiums->first()->id,
                'company_name' => 'Portões Seguros Ltda',
                'trade_name' => 'Portões Seguros',
                'cnpj' => '23.456.789/0001-01',
                'cpf' => null,
                'supplier_type' => 'company',
                'category' => 'gate_maintenance',
                'contact_name' => 'Maria Santos',
                'email' => 'maria@portoesseguros.com.br',
                'phone' => '(11) 2345-6789',
                'mobile' => '(11) 98765-4321',
                'address' => 'Av. dos Portões, 456',
                'number' => '456',
                'cep' => '02345-678',
                'city' => 'São Paulo',
                'state' => 'SP',
                'district' => 'Centro',
                'services_description' => 'Manutenção e reparo de portões automáticos e manuais.',
                'hourly_rate' => 85.00,
                'monthly_rate' => null,
                'contract_start' => '2024-03-01',
                'contract_end' => '2025-02-28',
                'status' => 'active',
                'evaluation' => 4.8,
                'notes' => 'Excelente qualidade de serviço.',
                'emergency_contact' => '(11) 99999-2222',
                'active' => true
            ],
            // Manutenção de interfones
            [
                'condominium_id' => $condominiums->first()->id,
                'company_name' => 'Interfones Tech Ltda',
                'trade_name' => 'Interfones Tech',
                'cnpj' => '34.567.890/0001-12',
                'cpf' => null,
                'supplier_type' => 'company',
                'category' => 'intercom_maintenance',
                'contact_name' => 'Roberto Lima',
                'email' => 'contato@interfonestech.com.br',
                'phone' => '(11) 3333-4444',
                'mobile' => '(11) 96543-2109',
                'address' => 'Rua da Tecnologia, 321',
                'number' => '321',
                'cep' => '04567-890',
                'city' => 'São Paulo',
                'state' => 'SP',
                'district' => 'Jardim Tech',
                'services_description' => 'Manutenção e instalação de sistemas de interfone.',
                'hourly_rate' => 95.00,
                'monthly_rate' => null,
                'contract_start' => '2024-01-15',
                'contract_end' => '2025-01-14',
                'status' => 'active',
                'evaluation' => 4.7,
                'notes' => 'Equipe bem treinada, serviço 24h.',
                'emergency_contact' => '(11) 99999-4444',
                'active' => true
            ],
            // Zeladoria e limpeza
            [
                'condominium_id' => $condominiums->first()->id,
                'company_name' => 'Limpeza Total Serviços',
                'trade_name' => 'Total Clean',
                'cnpj' => '45.678.901/0001-23',
                'cpf' => null,
                'supplier_type' => 'company',
                'category' => 'cleaning',
                'contact_name' => 'Ana Costa',
                'email' => 'ana@totalclean.com.br',
                'phone' => '(11) 4444-5555',
                'mobile' => '(11) 95432-1098',
                'address' => 'Rua da Limpeza, 654',
                'number' => '654',
                'cep' => '05678-901',
                'city' => 'São Paulo',
                'state' => 'SP',
                'district' => 'Jardim Limpo',
                'services_description' => 'Zeladoria completa, limpeza de áreas comuns e conservação predial.',
                'hourly_rate' => null,
                'monthly_rate' => 2500.00,
                'contract_start' => '2024-06-01',
                'contract_end' => '2024-11-30',
                'status' => 'active',
                'evaluation' => 4.9,
                'notes' => 'Excelente trabalho com plantas, muito cuidadosa.',
                'emergency_contact' => '(11) 99999-5555',
                'active' => true
            ],
            // Portaria
            [
                'condominium_id' => $condominiums->first()->id,
                'company_name' => 'Segurança Prime Ltda',
                'trade_name' => 'Prime Security',
                'cnpj' => '56.789.012/0001-34',
                'cpf' => null,
                'supplier_type' => 'company',
                'category' => 'reception',
                'contact_name' => 'Lucas Ferreira',
                'email' => 'contato@primesecurity.com.br',
                'phone' => '(11) 5555-6666',
                'mobile' => '(11) 93210-9876',
                'address' => 'Rua da Segurança, 147',
                'number' => '147',
                'cep' => '06789-012',
                'city' => 'São Paulo',
                'state' => 'SP',
                'district' => 'Vila Segura',
                'services_description' => 'Serviços de portaria, recepção e vigilância.',
                'hourly_rate' => null,
                'monthly_rate' => 4500.00,
                'contract_start' => '2024-02-01',
                'contract_end' => '2025-01-31',
                'status' => 'active',
                'evaluation' => 4.1,
                'notes' => 'Serviço trimestral, produtos certificados.',
                'emergency_contact' => '(11) 99999-6666',
                'active' => true
            ],
            // Controle de acesso
            [
                'condominium_id' => $condominiums->first()->id,
                'company_name' => 'Access Control Pro Ltda',
                'trade_name' => 'Access Pro',
                'cnpj' => '67.890.123/0001-45',
                'cpf' => null,
                'supplier_type' => 'company',
                'category' => 'access_control',
                'contact_name' => 'Ricardo Santos',
                'email' => 'contato@accesspro.com.br',
                'phone' => '(11) 6666-7777',
                'mobile' => '(11) 92109-8765',
                'address' => 'Rua do Controle, 258',
                'number' => '258',
                'cep' => '07890-123',
                'city' => 'São Paulo',
                'state' => 'SP',
                'district' => 'Alto Controle',
                'services_description' => 'Sistemas de controle de acesso, catracas e portões automáticos.',
                'hourly_rate' => null,
                'monthly_rate' => 1200.00,
                'contract_start' => '2024-01-01',
                'contract_end' => '2026-12-31',
                'status' => 'active',
                'evaluation' => 4.6,
                'notes' => 'Contrato de 3 anos, atendimento 24h.',
                'emergency_contact' => '(11) 99999-7777',
                'active' => true
            ],
            // Jardinagem
            [
                'condominium_id' => $condominiums->first()->id,
                'company_name' => 'Ana Costa - Jardinagem',
                'trade_name' => 'Jardins da Ana',
                'cnpj' => null,
                'cpf' => '987.654.321-09',
                'supplier_type' => 'individual',
                'category' => 'gardening',
                'contact_name' => 'Ana Costa',
                'email' => 'ana.jardins@outlook.com',
                'phone' => '(11) 7777-8888',
                'mobile' => '(11) 91098-7654',
                'address' => 'Rua das Flores, 654',
                'number' => '654',
                'cep' => '08901-234',
                'city' => 'São Paulo',
                'state' => 'SP',
                'district' => 'Jardim Botânico',
                'services_description' => 'Manutenção de jardins, poda de árvores e paisagismo.',
                'hourly_rate' => 60.00,
                'monthly_rate' => null,
                'contract_start' => null,
                'contract_end' => null,
                'status' => 'active',
                'evaluation' => 4.9,
                'notes' => 'Excelente trabalho com plantas, muito cuidadosa.',
                'emergency_contact' => null,
                'active' => true
            ],
            // Manutenção de elevadores
            [
                'condominium_id' => $condominiums->first()->id,
                'company_name' => 'Elevadores Seguros S.A.',
                'trade_name' => 'Seguros Elevadores',
                'cnpj' => '78.901.234/0001-56',
                'cpf' => null,
                'supplier_type' => 'company',
                'category' => 'elevator_maintenance',
                'contact_name' => 'Fernanda Aquino',
                'email' => 'manutencao@elevadoresseguros.com.br',
                'phone' => '(11) 8888-9999',
                'mobile' => '(11) 91098-7654',
                'address' => 'Av. Vertical, 369',
                'number' => '369',
                'cep' => '09012-345',
                'city' => 'São Paulo',
                'state' => 'SP',
                'district' => 'Alto da Serra',
                'services_description' => 'Manutenção preventiva e corretiva de elevadores.',
                'hourly_rate' => null,
                'monthly_rate' => 1200.00,
                'contract_start' => '2024-04-01',
                'contract_end' => '2025-03-31',
                'status' => 'active',
                'evaluation' => 4.4,
                'notes' => 'Especializada em elevadores de condomínios.',
                'emergency_contact' => '(11) 99999-8888',
                'active' => true
            ],
            // Manutenção da academia
            [
                'condominium_id' => $condominiums->first()->id,
                'company_name' => 'Academia Fit Ltda',
                'trade_name' => 'Fit Manutenção',
                'cnpj' => '89.012.345/0001-67',
                'cpf' => null,
                'supplier_type' => 'company',
                'category' => 'gym_maintenance',
                'contact_name' => 'Pedro Oliveira',
                'email' => 'manutencao@fitmanutencao.com.br',
                'phone' => '(11) 9999-0000',
                'mobile' => '(11) 90000-0000',
                'address' => 'Rua da Academia, 789',
                'number' => '789',
                'cep' => '10123-456',
                'city' => 'São Paulo',
                'state' => 'SP',
                'district' => 'Vila Fitness',
                'services_description' => 'Manutenção de equipamentos de academia e aparelhos de ginástica.',
                'hourly_rate' => 100.00,
                'monthly_rate' => null,
                'contract_start' => '2024-05-01',
                'contract_end' => '2025-04-30',
                'status' => 'active',
                'evaluation' => 4.3,
                'notes' => 'Especializada em equipamentos de academia.',
                'emergency_contact' => '(11) 99999-9999',
                'active' => true
            ],
            // Empresa garantidora
            [
                'condominium_id' => $condominiums->first()->id,
                'company_name' => 'Garantia Total Ltda',
                'trade_name' => 'Garantia Total',
                'cnpj' => '90.123.456/0001-78',
                'cpf' => null,
                'supplier_type' => 'company',
                'category' => 'guarantee_company',
                'contact_name' => 'Carlos Pereira',
                'email' => 'contato@garantiatotal.com.br',
                'phone' => '(11) 0000-1111',
                'mobile' => '(11) 91111-1111',
                'address' => 'Av. das Garantias, 123',
                'number' => '123',
                'cep' => '11234-567',
                'city' => 'São Paulo',
                'state' => 'SP',
                'district' => 'Centro Financeiro',
                'services_description' => 'Serviços de garantia e cobrança de taxas de administração.',
                'hourly_rate' => null,
                'monthly_rate' => 500.00,
                'contract_start' => '2024-01-01',
                'contract_end' => '2024-12-31',
                'status' => 'active',
                'evaluation' => 4.2,
                'notes' => 'Empresa especializada em cobrança.',
                'emergency_contact' => '(11) 99999-0000',
                'active' => true
            ],
            // Administradora de condomínio
            [
                'condominium_id' => $condominiums->first()->id,
                'company_name' => 'Admin Condomínios Ltda',
                'trade_name' => 'Admin Condo',
                'cnpj' => '01.234.567/0001-89',
                'cpf' => null,
                'supplier_type' => 'company',
                'category' => 'condominium_admin',
                'contact_name' => 'Maria Silva',
                'email' => 'contato@admincondo.com.br',
                'phone' => '(11) 1111-2222',
                'mobile' => '(11) 92222-2222',
                'address' => 'Rua da Administração, 456',
                'number' => '456',
                'cep' => '12345-678',
                'city' => 'São Paulo',
                'state' => 'SP',
                'district' => 'Vila Admin',
                'services_description' => 'Administração completa de condomínios residenciais.',
                'hourly_rate' => null,
                'monthly_rate' => 3500.00,
                'contract_start' => '2024-01-01',
                'contract_end' => '2024-12-31',
                'status' => 'active',
                'evaluation' => 4.8,
                'notes' => 'Administradora experiente e confiável.',
                'emergency_contact' => '(11) 99999-1111',
                'active' => true
            ],
            // Síndico terceirizado
            [
                'condominium_id' => $condominiums->first()->id,
                'company_name' => 'Síndico Profissional Ltda',
                'trade_name' => 'Síndico Pro',
                'cnpj' => '12.345.678/0001-90',
                'cpf' => null,
                'supplier_type' => 'company',
                'category' => 'third_party_manager',
                'contact_name' => 'Roberto Lima',
                'email' => 'contato@sindicopro.com.br',
                'phone' => '(11) 2222-3333',
                'mobile' => '(11) 93333-3333',
                'address' => 'Av. do Síndico, 789',
                'number' => '789',
                'cep' => '13456-789',
                'city' => 'São Paulo',
                'state' => 'SP',
                'district' => 'Jardim Síndico',
                'services_description' => 'Serviços de síndico profissional terceirizado.',
                'hourly_rate' => null,
                'monthly_rate' => 2800.00,
                'contract_start' => '2024-01-01',
                'contract_end' => '2024-12-31',
                'status' => 'active',
                'evaluation' => 4.7,
                'notes' => 'Síndico experiente e dedicado.',
                'emergency_contact' => '(11) 99999-2222',
                'active' => true
            ],
            // Dedetização
            [
                'condominium_id' => $condominiums->first()->id,
                'company_name' => 'Dedetização Pro Ltda',
                'trade_name' => 'Pro Dedetização',
                'cnpj' => '23.456.789/0001-01',
                'cpf' => null,
                'supplier_type' => 'company',
                'category' => 'pest_control',
                'contact_name' => 'Lucas Ferreira',
                'email' => 'contato@prodedetizacao.com.br',
                'phone' => '(11) 3333-4444',
                'mobile' => '(11) 94444-4444',
                'address' => 'Rua do Controle, 147',
                'number' => '147',
                'cep' => '14567-890',
                'city' => 'São Paulo',
                'state' => 'SP',
                'district' => 'Vila Limpa',
                'services_description' => 'Dedetização, desratização e controle de pragas urbanas.',
                'hourly_rate' => null,
                'monthly_rate' => 800.00,
                'contract_start' => '2024-02-01',
                'contract_end' => '2025-01-31',
                'status' => 'active',
                'evaluation' => 4.1,
                'notes' => 'Serviço trimestral, produtos certificados.',
                'emergency_contact' => '(11) 99999-6666',
                'active' => true
            ],
            // Limpeza de reservatórios
            [
                'condominium_id' => $condominiums->first()->id,
                'company_name' => 'Água Limpa Ltda',
                'trade_name' => 'Água Limpa',
                'cnpj' => '34.567.890/0001-12',
                'cpf' => null,
                'supplier_type' => 'company',
                'category' => 'water_tank_cleaning',
                'contact_name' => 'Ana Costa',
                'email' => 'contato@agualimpa.com.br',
                'phone' => '(11) 4444-5555',
                'mobile' => '(11) 95555-5555',
                'address' => 'Av. das Águas, 258',
                'number' => '258',
                'cep' => '15678-901',
                'city' => 'São Paulo',
                'state' => 'SP',
                'district' => 'Água Limpa',
                'services_description' => 'Limpeza e desinfecção de reservatórios de água.',
                'hourly_rate' => null,
                'monthly_rate' => 600.00,
                'contract_start' => '2024-03-01',
                'contract_end' => '2025-02-28',
                'status' => 'active',
                'evaluation' => 4.5,
                'notes' => 'Especializada em limpeza de reservatórios.',
                'emergency_contact' => '(11) 99999-7777',
                'active' => true
            ]
        ];

        foreach ($suppliers as $supplierData) {
            Supplier::updateOrCreate(
                ['cnpj' => $supplierData['cnpj'], 'cpf' => $supplierData['cpf']],
                $supplierData
            );
        }

        $this->command->info('Fornecedores criados com sucesso!');
    }
}
